### ISSUE TITLE
GreenTea text report crash with python 3

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-os-tools#205]
### Description

Done command:
mbedgt -t DISCO_F746NG-IAR --report-text=report.txt

It's working on a PC with python 2.7 installed,
but not with a PC with python 3.7:

mbedgt: exporting to TEXT 'report.txt'...
mbedgt: unexpected error:
        'str' object has no attribute 'decode'
AttributeError: 'str' object has no attribute 'decode'

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-454*

**Comment by VeliMattiLahtela** [comment]
@jeromecoutant python3 reporting was fixed for mbedgt v1.7.3, could you try with that

**Comment by jamesbeyond** [comment]
Currently, 1.7.3 greentea on Pypi is not support python3,
the fix will be in the next greentea release, which will happen soon,
The next version will support python 3

Workaround:
pip3 install git+https://github.com/ARMmbed/mbed-os-tools.git@master#subdirectory=packages/mbed-greentea/

**Comment by jamesbeyond** [comment]
Hi @jeromecoutant,
we having a new release of mbed-greentea 1.7.4, https://pypi.org/project/mbed-greentea/
would you able to confirm this issue is fixed, and closing the issue?

**Comment by jamesbeyond** [comment]
We think this issue been fixed. please re-open the ticket if you still experience this issue
