### PR TITLE
Fix string handling in different python versions

### PR DESCRIPTION
**Pull request by OPpuolitaival**
### Description

Fix for:
```
mbedgt: exporting to JUNIT file 'results/report_greentea_K66F_GCC_ARM.xml'...
mbedgt: exporting to HTML file 'results/report_greentea_K66F_GCC_ARM.html'...
mbedgt: unexpected error:
	'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\jenkins\mbed-os-pyenv-python3.7-default\Scripts\mbedgt.exe\__main__.py", line 9, in <module>
  File "c:\jenkins\mbed-os-pyenv-python3.7-default\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 357, in main
    cli_ret = main_cli(opts, args)
  File "c:\jenkins\mbed-os-pyenv-python3.7-default\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 1017, in main_cli
    html_report = exporter_html(test_report)
  File "c:\jenkins\mbed-os-pyenv-python3.7-default\lib\site-packages\mbed_os_tools\test\mbed_report_api.py", line 751, in exporter_html
    test_results)
  File "c:\jenkins\mbed-os-pyenv-python3.7-default\lib\site-packages\mbed_os_tools\test\mbed_report_api.py", line 640, in get_result_overlay
    overlay_dropdowns = get_result_overlay_dropdowns(result_div_id, test_results)
  File "c:\jenkins\mbed-os-pyenv-python3.7-default\lib\site-packages\mbed_os_tools\test\mbed_report_api.py", line 601, in get_result_overlay_dropdowns
    test_results['single_test_output']
AttributeError: 'str' object has no attribute 'decode'
```

### Pull request type

    [x ] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### CODE REVIEW

**Comment by theotherjimmy** [comment]
This is an improvement over #144 , but this does not work with python2.7. Could debug that?
