### ISSUE TITLE
Thread isAlive renamed to is_alive in Python 3.9

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-os-tools#247]
### Description

`mbedgt` doesn't work with Python 3.9:
```
mbedgt: running 1 test for platform 'NRF52840_DK' and toolchain 'ARMC6'                                                                                                                                           
        use 1 instance of execution threads for testing                                                                                                                                                           
mbedgt: could not generate test report'Thread' object has no attribute 'isAlive'                                                                                                                                  
mbedgt: completed in 1.53 sec
```

It's because `isAlive` has been renamed to `is_alive`. An update is needed at

https://github.com/ARMmbed/mbed-os-tools/blob/bb7f07fcf8352e89f2197ca0d0891a91c4e4e281/packages/mbed-greentea/mbed_greentea/mbed_greentea_cli.py#L907

Version:
```
$ mbedgt --version
1.7.4
```

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by tirkarthi** [comment]
I have created https://github.com/ARMmbed/mbed-os-tools/pull/248 as a fix

**Comment by LDong-Arm** [comment]
> I have created #248 as a fix

Thanks!
